config/routes.rb
Cadastro::Application.routes.draw do

  resources :products
  resources :people
  resource :sessions, {:only => [:new, :create, :destroy]}
  resources :users, {:except => [:show]}
  resources :tasks

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      # the user is one instance that come of the current_user method of class ApplicationController
      if user.id
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :height, :birthdate, :name
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :name, :weight
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :date, :description, :name

  paginates_per 3

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :password, :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery

    # disponibiliza o método publicamente
  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  # rails method to make public methods and accessibles
  # metodo do rails para tornar metodos publicos e acessiveis
  helper_method :current_user

  # this method raise one exception, preventing the access not authorized
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  skip_authorization_check

  check_authorization

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  respond_to :html, :js,:xml, :json
# Este foi o primeiro método criado que instancia a classe Person.

  def new
    @person = Person.new
  end

# Este método instancia a classe Person e guarda na variável de instancia todos os
  def index
     @people = Person.all
     respond_to do |format|
       format.html
     end
  end

# Este metodo recebe como parametro o id de person e guarda na variavel de instancia.
# o metodo salva no banco as informações de @person que foram passadas anteriormente, senão  renderiza o new novamente.
  def create
    @person = Person.new(params[:person])
    @person.save
    respond_with @person do |format|
      format.html { redirect_to @person }
    end
  end

# Este método está sendo chamado após o acionamento do botão "Click Person", a variavel de instancia está recebendo
# o id de person
  def show
    @person = Person.find(params[:id])
  end

  def destroy
    @person = Person.find(params[:id])# recebe como parametros as informações de person.
    @person.destroy #deleta as informações de person do banco.

    respond_to do |format|
      format.html {redirect_to people_path, notice: 'Person was successfully destroyed.'}
      format.json { head :no_content }
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    respond_to do |format|
      if @person.update_attributes(params[:person]) #metodo que atualiza person
          format.html {redirect_to person_path} #redireciona para o show
      else
          format.html { render action: "edit" } #renderiza o edit
      end
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  respond_to :html, :js

  def new
    @product = Product.new
  end

  def index
    @products = Product.all
    @product = Product.new

    respond_to do |format|
      format.html
    end
  end

  def create
    @product = Product.new(params[:product])
    @product.save

    respond_with @product
  end

  def show
    @product = Product.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    respond_with @product
  end

  def edit
    # @product = Product.find(params[:id])
    respond_with @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
         format.html {redirect_to product_path}
      else
         format.html {render action: "edit"}
      end
    end
  end

  #metodo que sera chamado na partial _list para mapear os dados do banco.
  def map_products
    Product.all #.all e um metodo do aplication_controller que retorna todos os registros do banco.
  end
  helper_method :map_products #permite que o metodo map_products seja acessado de fora da classe.

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @session = User.new
  end

  def create
    @session = User.find_by_user(params[:user][:user])

    if @session && (@session.password == params[:user][:password])

      session[:user_id] = @session.id

      redirect_to users_path, {:notice => "#{@session.user} was logged with success!"}

    else
      redirect_to new_sessions_path, {:notice => "Invalid user or password!"}
    end

  end

  def destroy
    session[:user_id] = nil
    redirect_to users_path
  end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # load_and_authorize_resource
  respond_to :html, :js, :xml, :json

  def new
    @task = Task.new
  end

  def create
    respond_with @task = Task.create(params[:task])
  end

  def show
    @task = Task.find(params[:id])
  end

  def index
    respond_with @tasks = Task.order("name").page(params[:page])
  end

  def destroy
    @task = Task.destroy(params[:id])

    if map_tasks.count != 0
      respond_with @task, :location => tasks_path(:page => params[:page])
    else
      respond_with @task, :location => tasks_path(:page => params[:page]) # para terminar
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    respond_with @task = Task.update(params[:id], params[:task])
  end

   #metodo que sera chamado na partial _list para mapear os dados do banco.
  def map_tasks
    Task.order("name").page(params[:page]) #Sets the number of elements per page, order by name.
  end
  helper_method :map_tasks #permite que o metodo map_products seja acessado de fora da classe.

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all

    respond_to do |format|
      format.html
      format.json {render json: @users}
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        # o redirect_to foi modificado para mostrar o index (lista de usuários)
        format.html { redirect_to users_path, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html {redirect_to users_url, notice:'User was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html{redirect_to users_path, notice: 'User was successfully updated.'}
        format.json{head :no_content}
      else
        format.html{render action: "edit"}
        format.json{render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Registration of people, products and tasks</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
    <%= notice %> <!--variavel criada posteriormente para exibir a mensagem no layout-->

    <script type="text/javascript">
      <%= yield %>
    </script>

    <!-- esta div exibe um id na tela que sera usado para efetuar o login da sessão -->
    <div id="session_id">
      <%= current_user.user if current_user %>
    </div>

  </body>

</html>

app/views/people/_form.html.haml
= simple_form_for @person, html: {id: "form"} do |f|
  = f.input :name
  = f.input :birthdate,  :label => "Birthdate", :as => :string
  = f.input :height
  = f.button :submit

app/views/people/edit.html.haml
%h1 Editing person

=render 'form'

=link_to 'List', people_path

app/views/people/index.html.haml
%h1 List of people
%table
  %tr
    %th Name
    %th Birthdate
    %th Height
  - @people.each do |person|
    %tr
      %td= person.name
      %td= person.birthdate
      %td= person.height
      %td= link_to 'Show', person_path(person)
      %td= link_to 'Edit', edit_person_path(person)
      %td= link_to 'Destroy', person, method: :delete, data:{confirm: 'Are you sure?'}
%br
= link_to 'Create new person', new_person_path

app/views/people/new.html.haml
%h1 New person

=render 'form'

=link_to 'Back', people_path

app/views/people/show.html.haml
Name:
= @person.name
%br
Birthdate:
= @person.birthdate
%br
Height:
= @person.height
%br

= link_to 'Edit', edit_person_path(@person)
= link_to 'People List', people_path

app/views/products/_edit.html.haml
%h1 Edit a product

=render 'form' #aqui está renderizando o _form.html.haml

=link_to 'List', products_path

app/views/products/_form.html.haml
= simple_form_for @product, html: {id: "form"}, :remote => true do |f|
  = f.input :name
  = f.input :weight
  = f.input :description
  = f.button :submit

app/views/products/_list.html.haml
%table
  %tr
    %th Name
    %th Weight
    %th Description
  - map_products.each do |product| #chamada do metodo map_products que guardara em cada objeto 'product' os seus atributos
    %tr
    %tr
    %tr
    %td= product.name
    %td= product.weight
    %td= product.description
    %td= link_to 'Show', product_path(product), :remote => true
    %td= link_to 'Edit', edit_product_path(product), :remote => true
    %td= link_to 'Destroy', product , method: :delete, data:{confirm: 'Are you sure?'}, :remote => true

app/views/products/_new.html.haml
%h1 New product

=render 'form' #aqui está renderizando o _form.html.haml

=link_to 'List', products_path

app/views/products/_show.html.haml
EXIBITION OF PRODUCT
%br
%br

Name:
= @product.name
%br
Description:
= @product.description
%br
Weight:
= @product.weight
%br

= link_to 'Edit', edit_product_path(@product), :remote => true
= link_to 'List', products_path

app/views/products/create.js.erb
<%-if @product.errors.any? %> //Ruby on Rails
  alert('Dont create product') //Javascript
<%-else %> //Ruby on Rails
  // $: function para obter um objeto html. Passando o parâmetro com uma tralha, ele obterá pelo id informado.
  // O método "html", insere um código html dentro desse objeto obtido com o jquery.
  $('#list').html("<%= escape_javascript render 'list' %>") //Javascript on Jquery
  alert('Created with success') //Javascript
<%-end %> //Ruby on Rails

app/views/products/destroy.js.erb
// condicao para testar erros (tag para testar codigo ruby:  <%-  %> )
<%- if @product.errors.any? %> // testa valor booleano? (se existir erro exibe msg de alerta)
  alert('Destroy error!') //mensagem
<%- else %>  //senao executa esta function JQUERY
  $('#list').html("<%= escape_javascript render 'list' %>") //O JQUERY armazena em uma div '#list'  o HTML que esta sendo passado (javascript)
<%- end %>

app/views/products/edit.js.erb
$('#io').html("<%= escape_javascript render 'edit' %>")

app/views/products/index.html.haml
%h1 List of products
/ esta carregando a 'div list' e renderizando a partial list
#list
  = render "list"
%br
= link_to 'Create product', new_product_path, :remote => true

/carrega a 'div io'  que sera exibida juntamente na mesma pagina com o 'list'
#io

#ed
%br

#sh

app/views/products/new.js.erb
<%- if @product.errors.any? %>
  alert('Dont create new product')
<%- else %>
  $('#io').html("<%= escape_javascript render 'new' %>")
  // alert('Created with success!')
<% end %>

app/views/products/show.js.erb
$('#io').html("<%= escape_javascript render 'show' %>")

app/views/tasks/_edit.html.haml
%h1 Edit a task

=render 'form'

=link_to 'List', tasks_path

app/views/tasks/_form.html.haml
= simple_form_for @task, html: {id: "form"}, :remote => true do |f|
  = f.input :name
  = f.input :date, :as => :string
  = f.input :description
  = f.button :submit

app/views/tasks/_list.html.haml
= paginate map_tasks

%table
  %tr
    %th Name
    %th Date
    %th Description
    - map_tasks.each do |task| #chamada do metodo map_tasks que guardara em cada objeto 'tasks' os seus atributos
      %tr
      %tr
      %tr
      %td= task.name
      %td= task.date
      %td= task.description
      %td= link_to 'Show', task_path(task), :remote => true
      %td= link_to 'Edit', edit_task_path(task), :remote => true
      %td= link_to 'Destroy', task_path(task, page: params[:page]) , method: :delete, data:{confirm: 'Are you sure?'}#, :remote => true

app/views/tasks/_new.html.haml
%h1 New task

=render 'form'

=link_to 'List', tasks_path

app/views/tasks/_show.html.haml
Name:
= @task.name
%br
Date:
= @task.date
%br
Description:
= @task.description
%br

= link_to 'Edit', edit_task_path(@task)
= link_to 'Task List', tasks_path

app/views/tasks/create.js.erb
<%-if @task.errors.any? %>
  alert('Internal error!')
<%-else %>
  $('#list').html("<%= escape_javascript render 'list' %>")
  alert('Created with success!')
<%-end %>

app/views/tasks/destroy.js.erb
alert(<%= params[:page].class %>)

app/views/tasks/edit.js.erb
<%- if @task.errors.any? %>
  alert('Internal error!')
<%- else %>
  $('#io').html("<%= escape_javascript render 'edit' %>")
<%- end %>

app/views/tasks/index.html.haml
%h1 List of tasks

/ imprime na tela a quantidade de itens por pagina
= p @tasks.count
%br

/ # = p :location => tasks_path(:page => params[:page])

%br
/Esta carregando a 'div list' e renderizando a partial list
#list
  = render "list"

%br
%br
= link_to 'Create new task', new_task_path, :remote => true

/carrega a 'div io'  que sera exibida juntamente na mesma pagina com o 'list'
#io

app/views/tasks/new.js.erb
<%- if @task.errors.any? %>
  alert('Dont create new task')
<%- else %>
  $('#io').html("<%= escape_javascript render 'new' %>")
<%- end %>

app/views/tasks/update.js.erb
<%-if @task.errors.any? %>
  alert('Internal error!')
<%-else %>
  $('#list').html("<%= escape_javascript render 'list' %>")
  alert('Updated with success!')
<%-end %>

app/views/users/_form.html.haml
= simple_form_for @user, html: {id: "form_1"} do |f|
  = f.input :user
  = f.input :password
  = f.button :submit

app/views/users/edit.html.haml
%h1 Editing user

=render 'form'

=link_to 'list', users_path

app/views/users/index.html.haml
%h1 List of users
%table
  %tr
    %th Users
  - @users.each do |user|
    %tr
      %td= user.user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, method: :delete, data:  {confirm: 'Are you sure?'}
%br

=link_to 'New User', new_user_path

=link_to 'Sign Out', sessions_path, {method: :delete}

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Users List', users_path

= link_to 'Sign In', new_sessions_path

app/views/users/show.html.haml
User:
= @user.user
%br

= link_to 'Edit', edit_user_path(@user)
= link_to 'Users List', users_path